In [1]:
a = [10,11,12,13,14,15]

In [2]:
import numpy as np

In [6]:
n_a = np.array(a)

In [7]:
n_a

array([10, 11, 12, 13, 14, 15])

In [9]:
n_a[0]

10

In [12]:
n_a[1]

11

In [16]:
last_index = len(n_a)-1

In [17]:
n_a[last_index]

15

In [19]:
n_a[-2]

14

In [20]:
n_a[:3]

array([10, 11, 12])

In [21]:
n_a[3:6]

array([13, 14, 15])

In [22]:
n_a[3:]

array([13, 14, 15])

In [23]:
n_a[1:]

array([11, 12, 13, 14, 15])

In [26]:
n_b = np.array([100,101,102,103,104,105])

In [27]:
n_c = np.concatenate([n_a,n_b])

In [28]:
np.average(n_c)

57.5

In [29]:
n_random = np.random.random(10)

In [31]:
n_random

array([0.50971228, 0.04061891, 0.89293851, 0.12431319, 0.65622061,
       0.79331538, 0.58776209, 0.73191591, 0.89924801, 0.47471206])

In [34]:
np.max(n_random)

0.8992480144430625

In [35]:
np.min(n_random)

0.0406189102690061

In [36]:
np.sort(n_random)

array([0.04061891, 0.12431319, 0.47471206, 0.50971228, 0.58776209,
       0.65622061, 0.73191591, 0.79331538, 0.89293851, 0.89924801])

In [37]:
np.argsort(n_random)

array([1, 3, 9, 0, 6, 4, 7, 5, 2, 8], dtype=int64)

In [38]:
np.sort(n_random)

array([0.04061891, 0.12431319, 0.47471206, 0.50971228, 0.58776209,
       0.65622061, 0.73191591, 0.79331538, 0.89293851, 0.89924801])

In [43]:
np.sort(n_random)[::-1]

array([0.89924801, 0.89293851, 0.79331538, 0.73191591, 0.65622061,
       0.58776209, 0.50971228, 0.47471206, 0.12431319, 0.04061891])